language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - hhvm # on Trusty only
  - nightly

os: linux

env:
  - TMDB_APP_KEY=7d637f29355aba225bd62d7af21d38d5

before_script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

script:
  - php artisan test
